[package]
name = "tide"
edition = "2024"
authors = ["Alva Lin (alva2lin@yuheng.site)"]

[dependencies.Pyth]
git = "https://github.com/pyth-network/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "sui-contract-testnet"

[dependencies.Wormhole]
git = "https://github.com/wormhole-foundation/wormhole.git"
subdir = "sui/wormhole"
rev = "sui/testnet"
override = true

[addresses]
tide = "0x0"
